<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $reportTitle ?? 'Report' }} – {{ $company->name ?? 'HiveStack IntelliCash' }}</title>
    <style>
        * { box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 10pt; color: #1e293b; margin: 0; padding: 20px; line-height: 1.4; }
        .report-header { border-bottom: 2px solid #0f172a; padding-bottom: 12px; margin-bottom: 20px; }
        .report-header h1 { margin: 0; font-size: 16pt; font-weight: bold; color: #0f172a; }
        .report-header .company { font-size: 11pt; color: #475569; margin-top: 4px; }
        .report-header .period { font-size: 9pt; color: #64748b; margin-top: 2px; }
        table { width: 100%; border-collapse: collapse; margin: 12px 0; }
        th, td { padding: 8px 10px; text-align: left; border-bottom: 1px solid #e2e8f0; }
        th { background: #f1f5f9; font-weight: 600; color: #334155; font-size: 9pt; }
        .text-right { text-align: right; }
        .total-row { font-weight: bold; background: #f8fafc; }
        .subtotal-row { font-weight: 600; color: #475569; }
        .footer { margin-top: 24px; padding-top: 12px; border-top: 1px solid #e2e8f0; font-size: 8pt; color: #94a3b8; text-align: center; }
        .section-title { font-size: 11pt; font-weight: bold; color: #0f172a; margin: 16px 0 8px 0; }
    </style>
</head>
<body>
    <div class="report-header">
        <h1>{{ $reportTitle ?? 'Report' }}</h1>
        @if($company ?? null)
            <div class="company">{{ $company->name }}</div>
            @if($company->email ?? null)<div class="period">{{ $company->email }}</div>@endif
        @endif
        @if($period ?? null)<div class="period">{{ $period }}</div>@endif
    </div>
    @yield('content')
    <div class="footer">
        Generated by HiveStack IntelliCash on {{ now()->format('Y-m-d H:i') }} &nbsp;|&nbsp; Confidential
    </div>
</body>
</html>
